/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_hhu_bsinfo_net_ib_JNIIbnet */

#ifndef _Included_de_hhu_bsinfo_net_ib_JNIIbnet
#define _Included_de_hhu_bsinfo_net_ib_JNIIbnet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_hhu_bsinfo_net_ib_JNIIbnet
 * Method:    init
 * Signature: (SIIIIIIIIILde/hhu/bsinfo/net/ib/JNIIbnet/Callbacks;)Z
 */
JNIEXPORT jboolean JNICALL Java_de_hhu_bsinfo_net_ib_JNIIbnet_init
    (JNIEnv *, jclass, jshort, jint, jint, jint, jint, jint, jint, jint, jint, jint, jobject);

/*
 * Class:     de_hhu_bsinfo_net_ib_JNIIbnet
 * Method:    shutdown
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_hhu_bsinfo_net_ib_JNIIbnet_shutdown
    (JNIEnv *, jclass);

/*
 * Class:     de_hhu_bsinfo_net_ib_JNIIbnet
 * Method:    addNode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_de_hhu_bsinfo_net_ib_JNIIbnet_addNode
    (JNIEnv *, jclass, jint);

/*
 * Class:     de_hhu_bsinfo_net_ib_JNIIbnet
 * Method:    postBuffer
 * Signature: (SLjava/nio/ByteBuffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_hhu_bsinfo_net_ib_JNIIbnet_postBuffer
    (JNIEnv *, jclass, jshort, jobject, jint);

/*
 * Class:     de_hhu_bsinfo_net_ib_JNIIbnet
 * Method:    postFlowControlData
 * Signature: (SI)Z
 */
JNIEXPORT jboolean JNICALL Java_de_hhu_bsinfo_net_ib_JNIIbnet_postFlowControlData
    (JNIEnv *, jclass, jshort, jint);

#ifdef __cplusplus
}
#endif
#endif